### ISSUE TITLE
VPN: Random Port Forwarded

### ISSUE THREAD

**Issue by Lyndeno** [rasmus-kirk/nixarr#16]
**Is your feature request related to a problem? Please describe.**
Certain VPNs, in my case Private Internet Access, randomly choose the port forwarded everytime you connect. It would be cool if there was some way to automatically configure a service (at least transmission) and open the port in the firewall to use this port upon connection.

**Describe the solution you'd like**
I doubt the port could be written into the configuration file at runtime. I am not sure if transmission provides a method of changing the port while it is running (with the rest of the configuration file being untouched).

**Describe alternatives you've considered**
None

**Additional context**
Private internet access provides custom scripts which set up wg-quick configs. You must leave the script running to keep the forwarded port active. See here: https://github.com/pia-foss/manual-connections

**Comment by rasmus-kirk** [comment]
Thanks for raising this issue.

The VPN doesn't currently have a firewall, so this should not be a problem at the moment. This will probably change in the future, but it's not critical to me, and the changes need to be in the upstream [VPN-submodule](https://github.com/Maroka-chan/VPN-Confinement). Maybe this will be able to be done statefully (meaning not _only_ on rebuild), but it really depends on how it ends up being upstream, and how important something like this is to people.

Also, I won't be maintaining support for VPN-providers that does not provide a wg-quick configuration, as that would end up being potentially many edge-cases, for not much gain. I know that Mullvad and AirVpn suports them.

As for the port that transmission uses, this can be set in the Transmission web UI.
