### ISSUE TITLE
Add Usenet option

### ISSUE THREAD

**Issue by TobiasB91** [rasmus-kirk/nixarr#21]
**Is your feature request related to a problem? Please describe.**
I would like to use this single solution to manage my media server, but since I am not a torrent but a usenet user, I need to configure additional packages within nix.

**Describe the solution you'd like**
Since the transmission module is already part of this module, an option for usenet users would be appreciated. I'm not opinionated on any particular downloader, but there are options like [sabnzbd](https://github.com/sabnzbd/sabnzbd) or [nzbget](https://github.com/nzbget/nzbget)

**Describe alternatives you've considered**

**Additional context**

**Comment by rasmus-kirk** [comment]
Not opposed to this, but I won't personally implement it. You could use Nixarr for anything but usenet, and just add it manually to your nixos configuration, if you'd like.

**Comment by rlad78** [comment]
Really like the work y'all have done here @rasmus-kirk. I've had _education_ and _knowledge_ on usenet (cough) for many years now, so I might try to work on this. It would help me get more nix practice in as well c:
