### ISSUE TITLE
Users torrenter and streamer are not declared.

### ISSUE THREAD

**Issue by amerocu** [rasmus-kirk/nixarr#26]
**Describe the bug**

When using nixarr for the first time, the user "torrenter" and "streamer" are not automatically created.

**Expected behavior**

The user should be automatically defined as for the other services, or there should be in the documentation an example on how to configure these users.

**Comment by amerocu** [comment]
It seems that there is a "nixarr" option `nixarr.enable` to be enabled to have those users created.

Maybe it's not super easy to do it, but would be nice if from `nixarr.transmission.enable` and `nixarr.jellyfin.enable` the needed users/groups are created.

**Comment by rlad78** [comment]
@amerocu would you mind providing the bit of Nix config you have that sets the values for the Nixarr options?

The intended functionality of `nixarr.enable` (at least, from my perspective) is to allow easy toggling of all Nixarr services. This is helpful for multi-host flake setups, where you could programmatically enable or disable all Nixarr services depending on your host or other conditions. 

However...in practice, this doesn't exactly work the way I just described. We probably need to restrict building a service derivation only if both `nixarr.enable` and `nixarr.service-xyz.enable` are both true, or something like that.

**Comment by amerocu** [comment]
I have started my journey with enabling all the arr services, but forget to enable `arr.enable`, my bad.

```
{
  nixarr = {
      jellyfin.enable = true;
      bazarr.enable = true;
      lidarr.enable = true;
      prowlarr.enable = true;
      radarr.enable = true;
      readarr.enable = true;
      sonarr.enable = true;
      transmission.enable = true;
    };
};
```

This leads me to a broken configuration. I see a bit confusing to have `arr.transmission.enable`, `services.transmission.enable` and `arr.enable`.

I guess it depends on the aim of the project, but it could make sense to have `arr.enable` enable everything with sensible configuration and have the possibility to disable the single services with `services.transmission.enable` or `arr.transmission.enable`.

Otherwise, have an assertion that forces to enable `arr.enable` if any or the Arr services are enabled.

Not sure about the kill switch idea, ideally if you import a module, it needs to be enabled to function, and eventually you can code your logic on top.

**Comment by rasmus-kirk** [comment]
> Otherwise, have an assertion that forces to enable nixarr.enable if any or the Arr services are enabled.

This is the way, it's what the other dependent options do already. I just forgot it for this since it seemed "obvious" :shrug:. I can see how it's not for others though, so it's a fault on my end.

**Comment by rasmus-kirk** [comment]
Fixed in main
