### ISSUE TITLE
The option vpnnamespaces is used but not defined.

### ISSUE THREAD

**Issue by Yasso9** [rasmus-kirk/nixarr#30]
When I add nixarr as input of me nix flake, I have the error : "The option vpnnamespaces is used but not defined." when I rebuild my flake.

**Comment by rasmus-kirk** [comment]
I need more info to do anything about this, otherwise I'll just close the issue. What's the config?

**Comment by rasmus-kirk** [comment]
Closing unless more info is given.

**Comment by Yasso9** [comment]
Sorry for the late response and my bad explanation

I have indeed the same issue as @raj-magesh, but I managed to find a workaround by just having `nixarr.enable = true;` in the config where I do not use nixarr.

**Comment by rasmus-kirk** [comment]
I'll reopen this then
