### ISSUE TITLE
stable support if VPN-Confinement isn't used

### ISSUE THREAD

**Issue by tbaumann** [rasmus-kirk/nixarr#31]
**Is your feature request related to a problem? Please describe.**

I noticed that this module depends on unstable. I believe that's mainly the case because VPN-Confinement.

I wonder if it would make sense to only load the vpn module if vpn is even enabled (nixarr.vpn.enable = true). That way it could be used on stable with reduced feature set.

**Describe the solution you'd like**
If VPN-Confinement is the only reason to only work on nixpkgs-unstable, then perhaps make it optional.

No worries if it's not worth it. I will cycle back to this again once I ave my actual media server. Perhaps I will just run it on unstable and sooner or later it will probably work on stable anyway...

**Comment by Maroka-chan** [comment]
VPN-Confinement does not need unstable. The nixpkgs input in its flake is only used to define tests that I run when working on the module.
The module itself uses your own nixpkgs version as it gets all its attributes from your call to `lib.nixosSystem`.
I use `nixos-24.05-small` with the module myself, so unless Nixarr is dependent on unstable, you should be able to make it follow your own version of nixpkgs.

**Comment by tbaumann** [comment]
Oh I may have jumped to conclusions. Then Nixarr itself is the issue.

@Maroka-chan great work on VPN confinement BTW. It's a really cool idea. I think I will use that later for something unrelated. (Routing different VPN so different vlan/ssid)
