### ISSUE TITLE
qbittorrent instead of transmission

### ISSUE THREAD

**Issue by ilovethensa** [rasmus-kirk/nixarr#36]
**Is your feature request related to a problem? Please describe.**
Its more of a personal thing, qbittorrent works better for me

**Describe the solution you'd like**
Well a new module for qbittorrent is added

**Describe alternatives you've considered**
Using transmission

**Additional context**
N/A

**Comment by rasmus-kirk** [comment]
qbittorrent cannot be configured using nix (no JSON), so I am reluctant to support this.

The reason that transmission runs under the `torrenter` user, however, is such that an additional client could be added in the future. You're welcome to submit a PR.

**Comment by StealthBadger747** [comment]
@rasmus-kirk If you are open to it, I can upstream the overlay I made for qBittorrent in Nixarr https://github.com/StealthBadger747/nix-multi-arch-lab/blob/e53e0e56ef882934d9d5259f439dbe1368d60f9c/modules/overlays/nixarr/qbittorrent.nix
