### ISSUE TITLE
Janitorr support

### ISSUE THREAD

**Issue by ilovethensa** [rasmus-kirk/nixarr#37]
**Is your feature request related to a problem? Please describe.**
No its not

**Describe the solution you'd like**
A module for janitorr is added

**Describe alternatives you've considered**
Deleting the media myself

**Additional context**

**Comment by rasmus-kirk** [comment]
Janitorr is not in nixpkgs, furthermore, I don't see the point of adding it to Nixarr specifically rather than just adding it to nixpkgs.
